### ISSUE TITLE
Add qpdf

### ISSUE THREAD

**Issue by krlmlr** [krlmlr-archive/r-portable#20]
Needed for compression of vignettes.

Download e.g. from http://sourceforge.net/projects/qpdf/files/qpdf/5.1.2/.

Closes krlmlr/r-appveyor#24.

CC @qinwf.

**Comment by maelle** [comment]
Since the issue is still open, I guess it's "normal" to get the WARNING "'qpdf' is needed for checks on size reduction of PDFs"?  https://ci.appveyor.com/project/ropenscilabs/monkeylearn

**Comment by krlmlr** [comment]
R shouldn't need qpdf for HTML vignettes in the first place, but a patch to fix this is still being processed. Can you please try setting the environment variable `R_QPDF=true`?

**Comment by krlmlr** [comment]
Or set `_R_CHECK_DOC_SIZES_=false`:

https://github.com/wch/r-source/blob/780021752eb83a71e2198019acf069ba8741103b/src/library/tools/R/check.R#L3576-L3578

**Comment by krlmlr** [comment]
Looks like it worked. Care to send a PR for r-appveyor?

R issue submitted, too: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17142

**Comment by maelle** [comment]
Yes it seems to have worked. thanks a lot! 

The PR should just be completing the README of r-appveyor with the description of this environment variable, right?

**Comment by krlmlr** [comment]
Thanks. I think it's safe to set `R_QPDF=true` for the `R CMD check` run.

**Comment by maelle** [comment]
You mean in the `R_CHECK_ARGS` of the Travis script then?

**Comment by krlmlr** [comment]
Or better `_R_CHECK_DOC_SIZES_=false`; you could also add a dummy vignette to the test package to verify that the fix actually works.

**Comment by maelle** [comment]
Actually there is a dummy vignette already -- but I guess it's too small

**Comment by maelle** [comment]
When I build the current fake package on my PC I get the qpdf warning, but it seems to already build alright on Appveyor, so I'm not sure what I should add to the dummy vignette to make the build fail.

**Comment by krlmlr** [comment]
The difference is most likely that you have built vignettes in your repository. Is there a specific reason to  include built vignettes in the repository?

**Comment by maelle** [comment]
You're right. I included them because I'm not building them again on Appveyor (API issues) but maybe that's not the kind of things r-appveyor should help one doing? ;-)

**Comment by krlmlr** [comment]
No, this is a very valid use case. Should work now by default in r-appveyor.

**Comment by maelle** [comment]
Awesome!
